-- Add sample partners to database
INSERT INTO public.partners (name, category, description, address, phone, email, website, hours, rating, is_featured, services, is_published) VALUES
(
  'Veterinary Care Plus',
  'clinic',
  'Full-service veterinary clinic with emergency services and modern facilities',
  '123 Pet Street, Medical District',
  '+1-555-123-4567',
  'info@vetcareplus.com',
  'www.vetcareplus.com',
  '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-6pm", "saturday": "10am-4pm", "sunday": "closed"}',
  4.8,
  true,
  '["vaccinations", "surgery", "dental", "emergency", "ultrasound", "x-ray", "lab"]',
  true
),
(
  'PetMeds Pharmacy',
  'pharmacy',
  'Online and in-store pet medications with veterinary consultation',
  '456 Medicine Ave, Downtown',
  '+1-555-234-5678',
  'pharmacy@petmeds.com',
  'www.petmeds.com',
  '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-9pm", "saturday": "9am-8pm", "sunday": "10am-6pm"}',
  4.6,
  false,
  '["medications", "supplements", "prescription", "delivery"]',
  true
),
(
  'Premium Pet Supplies',
  'supplies',
  'Everything your pet needs - food, toys, beds, and accessories',
  '789 Pet Plaza, Shopping Center',
  '+1-555-345-6789',
  'shop@petpremium.com',
  'www.petpremium.com',
  '{"monday": "9am-7pm", "tuesday": "9am-7pm", "wednesday": "9am-7pm", "thursday": "9am-7pm", "friday": "9am-8pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}',
  4.7,
  false,
  '["food", "toys", "beds", "collars", "grooming", "delivery"]',
  true
),
(
  'Pet Guardian Insurance',
  'insurance',
  'Comprehensive pet health insurance with affordable plans',
  '321 Insurance Blvd, Financial District',
  '+1-555-456-7890',
  'claims@petguardian.com',
  'www.petguardian.com',
  '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}',
  4.5,
  false,
  '["health_insurance", "accident_coverage", "wellness_plans", "claims"]',
  true
),
(
  'Nutrition Pro - Pet Food',
  'food',
  'Specialized pet nutrition with organic and prescription diets',
  '654 Nutrition Lane, Health District',
  '+1-555-567-8901',
  'nutrition@petpro.com',
  'www.petpro.com',
  '{"monday": "10am-6pm", "tuesday": "10am-6pm", "wednesday": "10am-6pm", "thursday": "10am-6pm", "friday": "10am-7pm", "saturday": "10am-5pm", "sunday": "closed"}',
  4.9,
  false,
  '["organic_food", "prescription_diet", "supplements", "consultation"]',
  true
),
(
  'Pawsitively Clean Grooming',
  'grooming',
  'Professional grooming services with spa treatments',
  '987 Beauty Street, Downtown',
  '+1-555-678-9012',
  'book@pawsitivelyClean.com',
  'www.pawsitivelyClean.com',
  '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-7pm", "saturday": "9am-5pm", "sunday": "closed"}',
  4.8,
  false,
  '["grooming", "spa", "nail_care", "teeth_cleaning", "styling"]',
  true
);
