-- Add comprehensive knowledge documents for all pet species

-- CAT DOCUMENTS
INSERT INTO public.knowledge_documents (id, title, category, species, content, is_published) VALUES
('cat-1', 'Cat Nutrition and Diet', 'nutrition', '["cat"]', 'Cats are obligate carnivores needing high-quality protein (30%+ for adults). Kittens need 30-40% protein. Feed 2-3 times daily for kittens, once daily for adults. Ensure adequate taurine intake (essential amino acid). Wet food helps maintain hydration. Fresh water essential daily.', true),
('cat-2', 'Cat Health and Wellness', 'prevention', '["cat"]', 'Cats need FVRCP vaccine (feline viral rhinotracheitis, calicivirus, panleukopenia) and rabies. Dental care crucial - brush teeth regularly. Monitor litter box habits (changes indicate illness). Annual exams recommended. Spay/neuter recommended. Common issues: ear infections, dental disease, kidney disease.', true),
('cat-3', 'Cat Medication Safety', 'medication', '["cat"]', 'Always store medications in original labeled containers. Never give human medications to cats. Common safe medications: amoxicillin, aspirin (with vet approval). Toxic: acetaminophen, ibuprofen, lilies, chocolate. If accidental exposure, contact vet immediately. Cats are sensitive to many medications.', true);

-- RABBIT DOCUMENTS
INSERT INTO public.knowledge_documents (id, title, category, species, content, is_published) VALUES
('rabbit-1', 'Rabbit Nutrition and Diet', 'nutrition', '["rabbit"]', 'Rabbits need unlimited timothy hay (80% of diet), fresh vegetables (leafy greens), and limited pellets. Provide 1 cup pellets per 5 lbs body weight daily. Fresh water essential. Avoid: iceberg lettuce, beans, grains. Hay keeps teeth healthy and aids digestion. Different hay varieties prevent boredom.', true),
('rabbit-2', 'Rabbit Health and Habitat', 'prevention', '["rabbit"]', 'Rabbits need spacious enclosures (minimum 4x2 feet), good ventilation, cool temperatures (60-70°F). Provide hiding spots and enrichment. Avoid: heat, humidity, loud noises. Regular health checks for snuffles (respiratory), overgrown teeth, and ear mites. Dental care is crucial - check teeth monthly.', true),
('rabbit-3', 'Rabbit Emergency: GI Stasis', 'medication', '["rabbit"]', 'GI stasis is life-threatening in rabbits. Signs: no appetite, no droppings, lethargy, grinding teeth, hunched posture. Immediate actions: offer unlimited timothy hay and water, gently massage abdomen, keep warm and quiet. Contact exotic vet SAME DAY - can be fatal within hours. Causes: stress, dietary changes, insufficient fiber.', true);

-- BIRD DOCUMENTS
INSERT INTO public.knowledge_documents (id, title, category, species, content, is_published) VALUES
('bird-1', 'Bird Nutrition and Diet', 'nutrition', '["bird"]', 'Birds need varied diet: high-quality pellets (60%), fresh fruits/vegetables (30%), seeds/nuts (10%). Avoid: avocado, chocolate, salt, caffeine. Different species need different nutrition (parrots: nuts and seeds; canaries: millet). Fresh water daily. Calcium important for egg-laying females. Nutritional deficiencies cause feather and behavior problems.', true),
('bird-2', 'Bird Behavior and Habitat', 'prevention', '["bird"]', 'Birds need spacious cages (larger is better), natural light, and social interaction. Provide perches, toys, and foraging opportunities. Temperature 65-75°F optimal. Avoid: drafts, smoke, aerosols, non-stick cookware fumes. Vocal birds can be loud in early morning/evening. Regular vet check-ups for respiratory health. Boredom causes behavioral problems.', true),
('bird-3', 'Bird Emergency: Respiratory Distress', 'medication', '["bird"]', 'Respiratory emergency in birds: wheezing, tail bobbing, difficulty breathing, open mouth breathing, lethargy. Immediate actions: minimize stress and movement, keep environment warm (80-85°F), provide humidified air if available, avoid drafts or aerosols. Contact avian vet IMMEDIATELY - birds decline rapidly. Never use Teflon/PTFE cookware around birds.', true);

-- HORSE DOCUMENTS
INSERT INTO public.knowledge_documents (id, title, category, species, content, is_published) VALUES
('horse-1', 'Horse Nutrition and Feeding', 'nutrition', '["horse"]', 'Horses need unlimited hay/pasture (1.5-2.5% body weight daily), supplemented with grain/concentrates based on activity level. Working horses need more calories. Fresh water essential (5-10 gallons daily). Minerals and vitamins important - salt lick recommended. Feeding schedule should be consistent. Quality hay prevents colic and improves digestion.', true),
('horse-2', 'Horse Health and Veterinary Care', 'prevention', '["horse"]', 'Horses need annual vaccines (EWT: equine herpesvirus, influenza; tetanus booster annually). Dental care essential - float teeth annually. Hoof care every 6-8 weeks. Regular exercise maintains health. Watch for lameness, weight changes, lethargy. Colic is emergency - call vet immediately. Parasitic control important - deworming program needed.', true),
('horse-3', 'Horse Emergency: Colic', 'medication', '["horse"]', 'Colic is abdominal pain - potentially life-threatening. Signs: pawing, rolling, sweating, distended abdomen, lack of defecation, increased heart rate. Immediate actions: call vet immediately, walk horse gently to prevent rolling, do NOT give food or water, monitor vital signs, be prepared for emergency surgery. Colic can be fatal - always get professional help.', true);

-- GENERAL EMERGENCY GUIDES (ALL SPECIES)
INSERT INTO public.emergency_guides (id, title, species, symptoms, immediate_actions, when_to_call_vet, is_published) VALUES
('emg-cat-1', 'Cat Difficulty Breathing', '["cat"]', '["labored breathing", "mouth open", "lethargy", "blue gums", "unusual posture"]', '["Keep cat calm and stress-free", "Do NOT force handling", "Go to emergency vet immediately"]', 'Immediately - life-threatening', true),
('emg-rabbit-1', 'Rabbit Digestive Blockage', '["rabbit"]', '["no appetite", "no droppings", "lethargy", "grinding teeth", "hunched posture"]', '["Stop all treats", "Offer unlimited hay and water", "Gently massage abdomen", "Keep warm and quiet"]', 'Same day - can be fatal within hours', true),
('emg-bird-1', 'Bird Difficulty Breathing', '["bird"]', '["wheezing", "tail bobbing", "difficulty breathing", "open mouth breathing", "lethargy"]', '["Minimize stress", "Keep warm (80-85°F)", "Provide humidified air if available"]', 'Immediately - birds decline rapidly', true),
('emg-horse-1', 'Horse Colic', '["horse"]', '["pawing", "rolling", "sweating", "distended abdomen", "lack of defecation", "increased heart rate"]', '["Call vet immediately", "Walk horse gently", "Do NOT give food or water", "Monitor vital signs"]', 'Immediately - life-threatening', true);
